# Case study : Classification of flowers -Iris dataset using Random Forest Algorithm

In [3]:
#install and import scikit learn library

!pip install sklearn
import sklearn

# Loading the library with the iris dataset

from sklearn.datasets import load_iris

Requirement already satisfied: sklearn in c:\users\prati\appdata\local\programs\python\python39\lib\site-packages (0.0)
Requirement already satisfied: scikit-learn in c:\users\prati\appdata\local\programs\python\python39\lib\site-packages (from sklearn) (0.24.2)
Requirement already satisfied: scipy>=0.19.1 in c:\users\prati\appdata\local\programs\python\python39\lib\site-packages (from scikit-learn->sklearn) (1.7.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\prati\appdata\local\programs\python\python39\lib\site-packages (from scikit-learn->sklearn) (2.2.0)
Requirement already satisfied: numpy>=1.13.3 in c:\users\prati\appdata\local\programs\python\python39\lib\site-packages (from scikit-learn->sklearn) (1.21.1)
Requirement already satisfied: joblib>=0.11 in c:\users\prati\appdata\local\programs\python\python39\lib\site-packages (from scikit-learn->sklearn) (1.0.1)

WARNING: You are using pip version 20.2.3; however, version 21.2.4 is available.
You should consider upgrading via the 'c:\users\prati\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.

In [4]:
# loading Scikit's random forest classifier library

from sklearn.ensemble import RandomForestClassifier

In [5]:
# loading pandas
import pandas as pd

In [6]:
# loading numpy
import numpy as np

In [7]:
# setting random seed
np.random.seed(0)

In [8]:
# creating an object called iris with the iris data
iris=load_iris()

In [21]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== ==== ======= ===== ====================\n\n    :Missing Attribute Values: None\n    :Class Distribution: 33.3% for each of 3 classes.\n    :Creator: R.A. Fisher\n    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n    :Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. topic:: References\n\n   - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n     Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n     Mathematical Statistics" (John Wiley, NY, 1950).\n   - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n   - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n     Structure and Classification Rule for Recognition in Partially Exposed\n     Environments".  IEEE Transactions on Pattern Analysis and Machine\n     Intelligence, Vol. PAMI-2, No. 1, 67-71.\n   - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n     on Information Theory, May 1972, 431-433.\n   - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n     conceptual clustering system finds 3 classes in the data.\n   - Many, many more ...',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'c:\\users\\prati\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\sklearn\\datasets\\data\\iris.csv'}

In [15]:
# creating a dataframe with the four feature variables
df=pd.DataFrame(iris.data,columns=iris.feature_names)

In [16]:
# viewing the top 5 rows
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [18]:
# Adding a new column for the species name
df['species']=pd.Categorical.from_codes(iris.target,iris.target_names)

In [19]:
# viewing the top 5 rows
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [23]:
# Creating Test and Train Data

df['is_train']=np.random.uniform(0,1,len(df)) <=0.75

In [24]:
# viewing the top 5 rows
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species,is_train
0,5.1,3.5,1.4,0.2,setosa,True
1,4.9,3.0,1.4,0.2,setosa,True
2,4.7,3.2,1.3,0.2,setosa,True
3,4.6,3.1,1.5,0.2,setosa,True
4,5.0,3.6,1.4,0.2,setosa,True

In [25]:
# Creating dataframes with test rows and training rows

train,test= df[df['is_train']==True],df[df['is_train']==False]

In [26]:
# Show the number of observations for the test and training dataframes

print('Number of observation in the training data:',len(train))
print('Number of observation in the test data:',len(test))

Number of observation in the training data: 118
Number of observation in the test data: 32

In [27]:
# Create a list of the feature column's names

features=df.columns[:4]

# View features

features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [29]:
# Converting each species name into digits

y= pd.factorize(train['species'])[0]

In [30]:
# viewing targert
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [31]:
# Creating a random forest classifier
clf= RandomForestClassifier(n_jobs=2,random_state=0)

In [32]:
# Training the classifier
clf.fit(train[features],y)

RandomForestClassifier(n_jobs=2, random_state=0)

In [34]:
# Applying the trained classifier to the test

clf.predict(test[features])

test[features]

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
10                 5.4               3.7                1.5               0.2
13                 4.3               3.0                1.1               0.1
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
20                 5.4               3.4                1.7               0.2
21                 5.1               3.7                1.5               0.4
23                 5.1               3.3                1.7               0.5
27                 5.2               3.5                1.5               0.2
31                 5.4               3.4                1.5               0.4
38                 4.4               3.0                1.3               0.2
52                 6.9               3.1                4.9               1.5
66                 5.6               3.0                4.5               1.5
68                 6.2               2.2                4.5               1.5
70                 5.9               3.2                4.8               1.8
72                 6.3               2.5                4.9               1.5
89                 5.5               2.5                4.0               1.3
98                 5.1               2.5                3.0               1.1
103                6.3               2.9                5.6               1.8
109                7.2               3.6                6.1               2.5
111                6.4               2.7                5.3               1.9
114                5.8               2.8                5.1               2.4
116                6.5               3.0                5.5               1.8
118                7.7               2.6                6.9               2.3
122                7.7               2.8                6.7               2.0
140                6.7               3.1                5.6               2.4
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
147                6.5               3.0                5.2               2.0
149                5.9               3.0                5.1               1.8

In [35]:
# Viewing the predicted probabilities of the first 10 observations

clf.predict_proba(test[features])[0:10]

array([[1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.95, 0.05, 0.  ],
       [1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ]])

In [36]:
# mapping names for the plants for each predicted plant class

pred=iris.target_names[clf.predict(test[features])]

In [37]:
# View the predicted species for the first five observations

pred[0:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [38]:
# Viewing the actual species for the first five observations

test['species'].head()

7     setosa
8     setosa
10    setosa
13    setosa
17    setosa
Name: species, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [41]:
# Creating confusion matrix
pd.crosstab(test['species'],pred,rownames=['Actual Species'],colnames=['Predicted Species'])

Predicted Species  setosa  versicolor  virginica
Actual Species
setosa                 13           0          0
versicolor              0           5          2
virginica               0           0         12

In [42]:
30/32

0.9375

In [45]:
print(clf.get_params())

{'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': 'auto', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_impurity_split': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_jobs': 2, 'oob_score': False, 'random_state': 0, 'verbose': 0, 'warm_start': False}

# Hyper Parameters
n_estimators = number of trees in the foreset
max_features = max number of features considered for splitting a node
max_depth = max number of levels in each decision tree
min_samples_split = min number of data points placed in a node before the node is split
min_samples_leaf = min number of data points allowed in a leaf node
bootstrap = method for sampling data points (with or without replacement)

# Random Hyperparameter Grid

In [47]:
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
print(random_grid)
{'bootstrap': [True, False],
 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, None],
 'max_features': ['auto', 'sqrt'],
 'min_samples_leaf': [1, 2, 4],
 'min_samples_split': [2, 5, 10],
 'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]}

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt'], 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None], 'min_samples_split': [2, 5, 10], 'min_samples_leaf': [1, 2, 4], 'bootstrap': [True, False]}

{'bootstrap': [True, False], 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, None], 'max_features': ['auto', 'sqrt'], 'min_samples_leaf': [1, 2, 4], 'min_samples_split': [2, 5, 10], 'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]}

In [50]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
#rf = RandomForestRegressor()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = clf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)
# Fit the random search model
rf_random.fit(train[features],y)

Fitting 3 folds for each of 100 candidates, totalling 300 fits

RandomizedSearchCV(cv=3,
                   estimator=RandomForestClassifier(n_jobs=2, random_state=0),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [10, 20, 30, 40, 50, 60,
                                                      70, 80, 90, 100, 110,
                                                      None],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=42, verbose=2)

In [52]:
output=rf_random.predict(test[features])

In [53]:
# mapping names for the plants for each predicted plant class

pred=iris.target_names[output]

In [54]:
# Creating confusion matrix
pd.crosstab(test['species'],pred,rownames=['Actual Species'],colnames=['Predicted Species'])

Predicted Species  setosa  versicolor  virginica
Actual Species
setosa                 13           0          0
versicolor              0           5          2
virginica               0           0         12

In [55]:
rf_random.best_params_

{'n_estimators': 400, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 30, 'bootstrap': True}

In [56]:
rf_random.cv_results_

{'mean_fit_time': array([0.8273472 , 4.44808364, 2.22903665, 2.95973333, 3.61511278,
       1.43637077, 1.54656569, 1.1133213 , 1.68767214, 3.1924603 ,
       0.98902313, 1.4938457 , 3.30391892, 2.85560934, 1.36995387,
       3.76075538, 1.61938445, 2.66994842, 4.08715669, 1.94480149,
       3.68149106, 3.52077897, 3.9919889 , 5.20979532, 3.1625456 ,
       0.91876896, 2.85598358, 2.72122677, 4.79147577, 3.77414266,
       2.73583293, 1.68388271, 1.78513718, 2.28226264, 4.78180989,
       1.9299287 , 3.16551987, 2.29533044, 2.18628446, 2.77380617,
       0.58348838, 1.62907036, 2.2570982 , 1.13885005, 0.49723593,
       2.53474927, 5.58781346, 0.90328232, 2.68753958, 1.33825429,
       3.6185135 , 4.32701238, 2.33295894, 2.02095691, 2.9133695 ,
       1.40398693, 4.12597775, 4.95776272, 4.14508486, 3.9594996 ,
       0.5610191 , 1.12404656, 1.94876798, 2.56254005, 4.36242286,
       4.43424543, 3.66433803, 3.67246763, 1.96793564, 4.07649732,
       2.88937394, 1.60104704, 4.57810235, 1.06902726, 4.13042752,
       0.87838546, 4.26293071, 5.30217322, 2.98054504, 0.63156422,
       3.87841543, 1.76191529, 2.63596956, 2.06760963, 1.9815565 ,
       1.36049978, 1.16231298, 4.13937998, 2.2705764 , 2.85286864,
       1.79132303, 3.99446805, 2.26678149, 1.68431346, 1.29242937,
       0.97428767, 2.01994594, 0.51740901, 4.93295439, 4.26750294]), 'std_fit_time': array([0.02031679, 0.09810553, 0.30045567, 0.11792987, 0.37927057,
       0.17978571, 0.05858668, 0.2091396 , 0.05983277, 0.15777821,
       0.07579253, 0.02763096, 0.07564619, 0.13245847, 0.11585764,
       0.12329327, 0.23443127, 0.0361129 , 0.44017725, 0.08209743,
       0.00476379, 0.43913893, 0.4686342 , 0.27974022, 0.14532097,
       0.04462684, 0.10044939, 0.06661117, 0.2432073 , 0.1907132 ,
       0.21073505, 0.10119708, 0.10989019, 0.13405825, 0.04550333,
       0.2119177 , 0.07407278, 0.22895133, 0.1538767 , 0.33254554,
       0.06747693, 0.08088464, 0.13725752, 0.09370579, 0.05765209,
       0.05025208, 0.1721736 , 0.13477679, 0.1225056 , 0.03827252,
       0.06056658, 0.29709007, 0.21919281, 0.05349597, 0.19773942,
       0.12955397, 0.02154658, 0.11485834, 0.47923314, 0.37166863,
       0.00293752, 0.09380379, 0.01781142, 0.24989485, 0.15504021,
       0.31886838, 0.12450753, 0.12039509, 0.05818261, 0.2337775 ,
       0.16211335, 0.0391989 , 0.01400784, 0.04158428, 0.0654403 ,
       0.16628898, 0.27032474, 0.0887901 , 0.38379379, 0.00704482,
       0.07970565, 0.35280063, 0.06448806, 0.14267406, 0.18508859,
       0.10482425, 0.10253975, 0.06989997, 0.11779918, 0.14830371,
       0.12350458, 0.13961609, 0.25874558, 0.0982816 , 0.2130436 ,
       0.05087045, 0.03344708, 0.11155012, 0.07748022, 0.54556468]), 'mean_score_time': array([0.10315776, 0.38019657, 0.29791514, 0.33683499, 0.28535167,
       0.1884559 , 0.23181995, 0.1256067 , 0.19804899, 0.37158672,
       0.12398807, 0.14950784, 0.4215521 , 0.32063023, 0.18991311,
       0.46857015, 0.17002996, 0.23950863, 0.44546556, 0.16056323,
       0.52306986, 0.38653183, 0.38970208, 0.43495202, 0.35074385,
       0.10692914, 0.38140241, 0.34985113, 0.59802906, 0.2877992 ,
       0.31374796, 0.20723645, 0.20600327, 0.20422387, 0.41336513,
       0.21330603, 0.28507439, 0.20167693, 0.20274941, 0.26496832,
       0.05771104, 0.16198969, 0.20465056, 0.12743314, 0.07880648,
       0.24938162, 0.57988707, 0.11491489, 0.28006426, 0.15538661,
       0.45427457, 0.48044586, 0.24598265, 0.2304546 , 0.3444171 ,
       0.15375352, 0.41274007, 0.39577111, 0.39937687, 0.31858468,
       0.08009831, 0.11330048, 0.24545145, 0.2786235 , 0.43452366,
       0.40927196, 0.4221096 , 0.333407  , 0.24984487, 0.46665827,
       0.4125607 , 0.29404243, 0.41528948, 0.11344512, 0.36643243,
       0.10334746, 0.40931122, 0.49145484, 0.26790849, 0.10177199,
       0.51982657, 0.17214235, 0.31383395, 0.2138381 , 0.22661217,
       0.14493553, 0.12198695, 0.374348  , 0.21541651, 0.25231417,
       0.15728879, 0.45791451, 0.23965168, 0.18245975, 0.17578149,
       0.10308305, 0.23006852, 0.07333684, 0.47201912, 0.35281428]), 'std_score_time': array([0.00152224, 0.02040863, 0.12529224, 0.00773302, 0.00394232,
       0.03195159, 0.02224842, 0.00663301, 0.01791413, 0.04028988,
       0.02522353, 0.00117099, 0.05798903, 0.02537967, 0.01569552,
       0.01848474, 0.01876597, 0.01023162, 0.07050387, 0.02162722,
       0.03149266, 0.01023438, 0.08725455, 0.02202629, 0.01617936,
       0.01669411, 0.06608867, 0.1202421 , 0.07565364, 0.0274781 ,
       0.01637671, 0.00472497, 0.04201954, 0.02660344, 0.02952357,
       0.01791238, 0.02841258, 0.02077684, 0.005167  , 0.01729355,
       0.00913317, 0.0114169 , 0.00895603, 0.01724071, 0.02134875,
       0.01962212, 0.03679509, 0.01143084, 0.01562561, 0.02026314,
       0.022746  , 0.01045535, 0.03202097, 0.01115242, 0.01189745,
       0.00607186, 0.01920269, 0.0149514 , 0.03468502, 0.00806725,
       0.02995003, 0.01081624, 0.00717263, 0.00993123, 0.06154463,
       0.06155323, 0.04229663, 0.04693356, 0.03648177, 0.0303256 ,
       0.03161095, 0.06446334, 0.01276288, 0.01730544, 0.00989095,
       0.00989722, 0.03052869, 0.01685918, 0.07254454, 0.04015386,
       0.03641334, 0.01914879, 0.09817705, 0.01373174, 0.02790185,
       0.00356997, 0.03020307, 0.02039905, 0.03013604, 0.01103703,
       0.01297966, 0.00730234, 0.04143786, 0.02695623, 0.02400381,
       0.00897112, 0.00652476, 0.00968686, 0.01677129, 0.06208531]), 'param_n_estimators': masked_array(data=[400, 2000, 1200, 2000, 1600, 800, 1000, 600, 1000,
                   1800, 400, 800, 2000, 1600, 800, 1800, 600, 1000, 1800,
                   600, 1800, 1600, 1400, 1800, 1400, 400, 1400, 1000,
                   2000, 1200, 1200, 800, 800, 800, 1800, 800, 1200, 800,
                   800, 1000, 200, 600, 800, 400, 200, 1000, 2000, 400,
                   1200, 600, 1800, 2000, 1000, 1000, 1400, 600, 1600,
                   1800, 1400, 1400, 200, 400, 1000, 1200, 1600, 1600,
                   1800, 1400, 1000, 2000, 1400, 800, 1800, 400, 1600,
                   400, 1600, 2000, 1000, 200, 2000, 600, 1000, 800, 800,
                   600, 400, 1600, 800, 1000, 600, 2000, 800, 600, 600,
                   400, 1000, 200, 2000, 2000],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value='?',
            dtype=object), 'param_min_samples_split': masked_array(data=[5, 5, 5, 2, 2, 5, 5, 5, 2, 5, 10, 5, 10, 5, 10, 2, 5,
                   2, 10, 5, 10, 5, 5, 2, 5, 2, 2, 5, 10, 2, 10, 2, 5, 10,
                   2, 10, 5, 2, 5, 2, 5, 10, 2, 10, 5, 2, 2, 10, 2, 2, 2,
                   10, 10, 5, 5, 2, 5, 2, 2, 10, 2, 2, 10, 10, 10, 10, 2,
                   2, 10, 10, 2, 2, 5, 5, 5, 10, 10, 5, 5, 5, 2, 10, 5,
                   10, 5, 10, 5, 2, 10, 10, 10, 5, 5, 2, 2, 10, 2, 5, 2,
                   10],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value='?',
            dtype=object), 'param_min_samples_leaf': masked_array(data=[1, 1, 2, 4, 4, 4, 2, 1, 1, 4, 4, 1, 1, 2, 2, 4, 2, 1,
                   2, 1, 1, 1, 4, 2, 1, 1, 1, 2, 4, 2, 4, 2, 1, 4, 4, 2,
                   2, 1, 2, 2, 4, 2, 4, 4, 2, 1, 2, 4, 4, 2, 1, 2, 4, 4,
                   2, 4, 1, 2, 1, 2, 1, 4, 4, 2, 1, 2, 4, 2, 1, 2, 4, 4,
                   2, 1, 1, 2, 1, 1, 2, 4, 4, 2, 4, 2, 4, 1, 1, 4, 4, 2,
                   1, 4, 1, 4, 4, 2, 1, 4, 2, 2],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value='?',
            dtype=object), 'param_max_features': masked_array(data=['sqrt', 'sqrt', 'sqrt', 'auto', 'sqrt', 'sqrt', 'sqrt',
                   'sqrt', 'auto', 'auto', 'auto', 'sqrt', 'sqrt', 'sqrt',
                   'sqrt', 'auto', 'auto', 'sqrt', 'auto', 'auto', 'sqrt',
                   'sqrt', 'sqrt', 'auto', 'sqrt', 'sqrt', 'auto', 'sqrt',
                   'auto', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt',
                   'sqrt', 'sqrt', 'auto', 'auto', 'sqrt', 'auto', 'sqrt',
                   'sqrt', 'sqrt', 'auto', 'sqrt', 'auto', 'sqrt', 'sqrt',
                   'sqrt', 'auto', 'auto', 'auto', 'auto', 'sqrt', 'sqrt',
                   'auto', 'auto', 'auto', 'sqrt', 'sqrt', 'sqrt', 'auto',
                   'auto', 'sqrt', 'auto', 'auto', 'auto', 'sqrt', 'auto',
                   'sqrt', 'sqrt', 'sqrt', 'auto', 'auto', 'sqrt', 'sqrt',
                   'sqrt', 'sqrt', 'auto', 'auto', 'auto', 'auto', 'auto',
                   'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt',
                   'sqrt', 'sqrt', 'auto', 'sqrt', 'auto', 'auto', 'auto',
                   'sqrt', 'auto'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value='?',
            dtype=object), 'param_max_depth': masked_array(data=[30, 10, 10, 30, 10, 30, 100, 60, 50, 10, 70, 90, 10,
                   10, 30, 50, 70, 20, 110, 80, 30, 70, 80, None, 80,
                   None, 40, 20, 100, 20, 20, 50, 100, 50, 90, 20, 20,
                   100, None, 60, 10, 60, 90, 90, 90, 110, 90, 80, 70,
                   110, 20, 50, 50, 30, None, 60, 10, 80, 100, 80, 50, 10,
                   80, None, 20, None, 10, 70, 80, 60, 80, 20, 60, 90, 90,
                   90, None, 100, 10, 80, 60, 100, 100, None, 70, 40, 100,
                   80, 100, 10, 110, None, 40, 40, 30, 40, 10, 100, 20,
                   40],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value='?',
            dtype=object), 'param_bootstrap': masked_array(data=[True, True, False, False, True, False, False, False,
                   False, False, True, False, False, False, False, False,
                   False, True, False, True, False, False, True, True,
                   False, False, False, True, False, True, False, False,
                   False, True, True, False, True, True, True, True, True,
                   True, True, True, False, True, True, False, False,
                   False, False, False, False, False, False, False, True,
                   True, True, True, True, True, False, False, True, True,
                   False, True, False, False, False, False, True, False,
                   True, False, True, True, True, True, False, True, True,
                   False, False, False, True, True, True, True, True,
                   False, True, True, False, False, False, False, True,
                   True],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value='?',

In [57]:
best_random = rf_random.best_estimator_

In [58]:
output=best_random.predict(test[features])

In [59]:
# mapping names for the plants for each predicted plant class

pred=iris.target_names[output]

In [60]:
# Creating confusion matrix
pd.crosstab(test['species'],pred,rownames=['Actual Species'],colnames=['Predicted Species'])

Predicted Species  setosa  versicolor  virginica
Actual Species
setosa                 13           0          0
versicolor              0           5          2
virginica               0           0         12